### ISSUE TITLE
Fisheye model

### ISSUE THREAD

**Issue by mhkabir** [AlejandroSilvestri/os1#1]
Hi, 

I found your fork, and it looks super-interesting. I'm interested in using fisheye stereo cameras (200 degree FOV) with ORBSLAM2. 

Do your you have any recommendations to achieve this? I saw a couple of commits which refer to your fisheye implementation, but more information on how to implemented it, calibration model, etc. would be appreciated :) 

Thanks!

**Comment by AlejandroSilvestri** [comment]
Hi @mhkabir , thank you.

My mentions about fisheye where in https://github.com/raulmur/ORB_SLAM2/issues/125 and https://github.com/raulmur/ORB_SLAM2/issues/220

I implemented a method for fisheye undistort in [antidistorsionarProyeccionEquidistante](https://github.com/AlejandroSilvestri/os1/blob/master/src/Frame.cc#L448).

It is a slightly modified copy from [cv::fisheye::undistortImage](http://docs.opencv.org/3.1.0/db/d58/group__calib3d__fisheye.html#gab738cdf90ceee97b2b52b0d0e7511541), the opencv implementation, which I don't know why I couldn't get working.(it crashed).

The paper is brief: [A Generic Camera Model and Calibration Method for Conventional, Wide-Angle, and Fish-Eye Lenses,](http://www.ee.oulu.fi/mvg/files/pdf/pdf_697.pdf) from Juho Kannala and Sami S. Brandt.

I couldn't get opencv's calibration application for fisheye, so I calibrate it "by hand": put a trackbar for each undistortion parameter, and move them until image is calibrated.

I found that in fisheye model is very important to cailbrate the center of the camera.  Actually I could calibrate one fisheye camera solely by determining its center.
