### ISSUE TITLE
Cannot find <pangolin/config.h>: No such file or directory

### ISSUE THREAD

**Issue by Roshnee** [AlejandroSilvestri/os1#15]
I am a beginner trying to get a hold in slam with live video streaming.
I tried to execute the program where I got an error stating the config.h file in pangolin is missing. 
```
/usr/local/include/Pangolin/include/pangolin/platform.h:30:29: fatal error: pangolin/config.h: No such file or directory
compilation terminated.
make: *** [src/FrameDrawer.o] Error 1
src/subdir.mk:94: recipe for target 'src/FrameDrawer.o' failed
```
I can find a config.h.in file in the src folder but it doesn't seem to solve the problem.
I have been stuck in it for the past few days. 

Could somebody please help.

**Comment by AlejandroSilvestri** [comment]
@Roshnee 

I'm not sure what is causing this problem.

Let's try installing Pangolin.  Pangolin's page show you how to build it.  After building it with cmake, try installing it with:

    $ make
    $ sudo make install

**Comment by Roshnee** [comment]
Thank you :) But I realized that the config.h file was located in the folder 'build/src/include/pangolin' :+1:

**Comment by YangJae96** [comment]
I faced the same problem. Could you help me please? 

 #include <pangolin/pangolin.h> No such File or Directory
error message comes out.
I found the pangolin.h >> header file in the   Pangolin/include/pangolin/  pangolin.h .
But i am not sure how to fix the problem. 
Can you help me I am also new to slam now..

**Comment by AlejandroSilvestri** [comment]
@YangJae96 ,

Try to write the full path in your #include, or add Pangolin folder to the include search path in your IDE.

**Comment by chapa17** [comment]
Hello,

@AlejandroSilvestri  I am facing the same issue while trying to use Pangolin in other library. I tried writing the full path but it then gives error for other pangolin header files. Can you please help me?

Thank you!
