### ISSUE TITLE
Error saving/loading map on windows

### ISSUE THREAD

**Issue by HugoAch** [AlejandroSilvestri/os1#18]
Hi,
I'm using software on Windows platform (Visual Studio project). I can save the map (binary file is generated), but I cannot load it, SW throws exception in boost binary load.
Furthermore, software throws multiple IWExceptions.
How can I fix this issue?
Thanks in advance.

**Comment by AlejandroSilvestri** [comment]
Hi @HugoAch 

This project is paused right now.  I'm able to load and save maps, but I noticed a bug that prevent loading when there is a loop closure.

Sorry I'm no able to fix it for the moment.

**Comment by HugoAch** [comment]
Hi,
I found solution for saving/loading map in windows.
I only need specify binary file type on mapLoad/mapSave function.

mapLoad
`std::ifstream is(archivo, ios_base::binary);`

mapSave
`std::ofstream os(archivo, ios_base::binary);`

Thanks for your reponse,
Regards
