### ISSUE TITLE
 Serializer.h: No such file or directory	

### ISSUE THREAD

**Issue by shening** [AlejandroSilvestri/os1#2]
Hi

Thank you for all the effort in putting this together is commenting it. I am currently trying to go through the comments and translate them to english. 

However I have a problem running the code in Ecliple and Ubuntu 14.04 . The original ORB_SLAM2 compiles fine on the system. 

The error I get is 
Description	Resource	Path	Location	Type
fatal error: Serializer.h: No such file or directory	KeyFrame.h	/os1/include	line 31	C/C++ Problem
 
Thank you

Sebastian

**Comment by AlejandroSilvestri** [comment]
@shening , this project miss some files I didn't add yet, like Serializer.h and Serializer.cc.
I hope I'll add them this week.

**Comment by AlejandroSilvestri** [comment]
@shening , please checkout PuntosLejanos branch.  It has both Serializer.cpp and Serializer.h .  And it works.
