### ISSUE TITLE
error in building

### ISSUE THREAD

**Issue by OmarHamdoun** [AlejandroSilvestri/os1#21]
make all 
Building target: os1
Invoking: Cross G++ Linker
g++ -L/usr/local/lib -L"/home/omar/work/os1-Video/Thirdparty" -o "os1"  ./src/Converter.o ./src/Frame.o ./src/FrameDrawer.o ./src/Initializer.o ./src/KeyFrame.o ./src/KeyFrameDatabase.o ./src/KeyFrameTriangulacion.o ./src/LocalMapping.o ./src/LoopClosing.o ./src/Map.o ./src/MapDrawer.o ./src/MapPoint.o ./src/ORBextractor.o ./src/ORBmatcher.o ./src/Optimizer.o ./src/PnPsolver.o ./src/PuntoLejano.o ./src/PuntosLejanosDB.o ./src/Serializer.o ./src/Sim3Solver.o ./src/System.o ./src/Tracking.o ./src/Video.o ./src/Viewer.o ./src/main.o   -lopencv_core -lDBoW2 -lboost_serialization -lpangolin -lopencv_features2d -lopencv_highgui -lpthread -lopencv_videoio -lopencv_imgcodecs -lopencv_imgproc -lopencv_calib3d -lGL -lGLU -lg2o
/usr/bin/ld: cannot find -lDBoW2
collect2: error: ld returned 1 exit status
make: *** [os1] Error 1
makefile:45: recipe for target 'os1' failed

**Comment by AlejandroSilvestri** [comment]
@OmarHamdoun , I cannot help hoy much, it seems you didn't generate IDBoW2.o 
The code is in Thirdparty folder, it's the same as in ORB-SLAM2, where you can find more help about this.

**Comment by OmarHamdoun** [comment]
thanks alot  but i think i have a problem with eclipse project
![screenshot_20181012_110525](https://user-images.githubusercontent.com/7859925/46856495-44dd8680-ce0f-11e8-9495-a1ceac52dca9.png)
