### ISSUE TITLE
when pushing Grabar mapa , System stop.

### ISSUE THREAD

**Issue by ghost** [AlejandroSilvestri/os1#3]
when pushing Grabar mapa , System stops.

Teclas:
w: Cambia el tamaño de las ventanas de imágenes.  Hay 3 tamaños: 100%, 50% y 25%.
u: Undistort, muestra la imagen de entrada antidistorsionada.

Si se procesa un archivo de video:
espacio: Pausa el video.
r: Reversa, invierte la secuencia de imágenes del video.
t: Tiempo entre cuadros.  Alterna entre varios períodos máximos.

Terminando el constructor SLAM.
Pangolin creado.
Ventana para frame.
init done
Local Mapping STOP
System Reseting

**Comment by AlejandroSilvestri** [comment]
Yes, I have some problems while saving or loading some maps.  The error happens while serializing vectors with boost.  I'll rewrite the vector serializing code.
