### ISSUE TITLE
Install Pangolin

### ISSUE THREAD

**Issue by vmhoff** [AlejandroSilvestri/os1#4]
When I compile the project on Eclipse, the error "pangolin/pangolin.h No such file or directory" occurs. I've installed the Pangolin and I can compile the original ORB-SLAM2 project on my PC without errors. The libraries on Eclipse project are equal the image https://github.com/AlejandroSilvestri/os1/blob/master/doc/Librerias.png
Should I do something else to set pangolin library up?

**Comment by AlejandroSilvestri** [comment]
@vmhoff ,

I believe eclipse is not findiing pangolin.h

I has it in /usr/local/include/pangolin/pangolin.h

/usr/local/include is one of those folders where compiler searches by default.

If you find it elsewhere, you can move to that folder, or you can rewrite the entire path in the code, I believe only in MapDrawer.h .

**Comment by vmhoff** [comment]
Hi, thanks for the answer.
Well, I've tried to add these folders to the Eclipse project, but it still didn't work. So I just adapted the CMakeLists.txt of the original project and it works for me.
