### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by ghost** [AlejandroSilvestri/os1#6]
Hi Alejandro,

Compile error happens..

home/t7810/work/ORB_SLAM2/src/Viewer.cc:286:4: error: no matching function for call to ‘ORB_SLAM2::FrameDrawer::DrawFrame(float, int)’
    );

Viewer.cc:286
cv::Mat imagenFrame = mpFrameDrawer->DrawFrame(
            		1/factorEscalaImagenParaMostrar,
					mpSystem->mpLocalMapper->AcceptKeyFrames()? -1 :  mpSystem->mpLocalMapper->KeyframesInQueue()
			);

**Comment by AlejandroSilvestri** [comment]
@takuhara ,

Thank you, your issue let me see I had some files not committed, I don't know why.
They are now committed.  You can pull them and recompile.
