### ISSUE TITLE
called mapLoad from the beginning without MonocularInitialization

### ISSUE THREAD

**Issue by yuyou** [AlejandroSilvestri/os1#8]
Hi

Thanks for the serialization code and it works nicely when the system has already a good map and some local map points. 

I made some changes to make it work in my situation where a map is loaded and the tracker state is set to LOST. In order to make it work, I manually added two lines in the end of the function "Serializer::mapLoad"

`
mapa->SetReferenceMapPoints(mapa->GetAllMapPoints());
Sistema->GetTracker()->mState = Tracking::LOST;
`

I am not sure it is correct but at least works. Without reference map points, my loaded map points will be culled away completely after few frames.

Regards,

Yu

**Comment by AlejandroSilvestri** [comment]
@yuyou ,

Thanks for the update.  I'll add the reference mappoints to the code.
I'm glad you found it usefull.

The state is already set to LOST in the function that calls mapLoad.


Right now I have an improved mapSave for big maps, that shrink many times the file size.  It didn't make it to the UI yet.  Right now you can toggle to "shrink map" pressing c (while focus on frame window).


And, if you are interested in how orb-slam2 work, I have a collaborator translating our spanish documentation to english.

**Comment by yuyou** [comment]
By using Google translate and doing copy&paste, Spanish comments already helped me a lot in understanding how ORB-SLAM2 works 👍  Any link available already for "official" English documentation?

Your new mapSave function is definitely interesting and I will check out later and understand more the internal structures.
